export const elements = {
    H: {
        name: 'Hidrógeno',
        symbol: 'H',
        atomicNumber: 1,
        atomicMass: 1.00784,
        group: '',
    },
    He: {
        name: 'Helio',
        symbol: 'He',
        atomicNumber: 2,
        atomicMass: 4.002602,
        group: '',
    },
    Li: {
        name: 'Litio',
        symbol: 'Li',
        atomicNumber: 3,
        atomicMass: 6.941,
        group: '',
    },
    Be: {
        name: 'Berilio',
        symbol: 'Be',
        atomicNumber: 4,
        atomicMass: 9.012182,
        group: '',
    },
    B: {
        name: 'Boro',
        symbol: 'B',
        atomicNumber: 5,
        atomicMass: 10.811,
        group: '',
    },
    C: {
        name: 'Carbono',
        symbol: 'C',
        atomicNumber: 6,
        atomicMass: 12.011,
        group: '',
    },
    N: {
        name: 'Nitrógeno',
        symbol: 'N',
        atomicNumber: 7,
        atomicMass: 14.0067,
        group: '',
    },
    O: {
        name: 'Oxígeno',
        symbol: 'O',
        atomicNumber: 9,
        atomicMass: 15.999,
        group: '',
    },
    F: {
        name: 'Flúor',
        symbol: 'F',
        atomicNumber: 9,
        atomicMass: 18.998403,
        group: '',
    },
    Ne: {
        name: 'Neón',
        symbol: 'Ne',
        atomicNumber: 10,
        atomicMass: 20.1797,
        group: '',
    },
    Na: {
        name: 'Sodio',
        symbol: 'Na',
        atomicNumber: 11,
        atomicMass: 22.989769,
        group: '',
    },
    Mg: {
        name: 'Magnesio',
        symbol: 'Mg',
        atomicNumber: 12,
        atomicMass: 24.305,
        group: '',
    },
    Al: {
        name: 'Aluminio',
        symbol: 'Al',
        atomicNumber: 13,
        atomicMass: 26.981539,
        group: '',
    },
    Si: {
        name: 'Silicio',
        symbol: 'Si',
        atomicNumber: 14,
        atomicMass: 28.0855,
        group: '',
    },
    P: {
        name: 'Fósforp',
        symbol: 'P',
        atomicNumber: 15,
        atomicMass: 30.97376,
        group: '',
    },
    S: {
        name: 'Azufre',
        symbol: 'S',
        atomicNumber: 16,
        atomicMass: 32.065,
        group: '',
    },
    Cl: {
        name: 'Cloro',
        symbol: 'Cl',
        atomicNumber: 17,
        atomicMass: 35.453,
        group: '',
    },
    Ar: {
        name: 'Argón',
        symbol: 'Ar',
        atomicNumber: 18,
        atomicMass: 39.948,
        group: '',
    },
    K: {
        name: 'Potasio',
        symbol: 'K',
        atomicNumber: 19,
        atomicMass: 39.0983,
        group: '',
    },
    Ca: {
        name: 'Calcio',
        symbol: 'Ca',
        atomicNumber: 20,
        atomicMass: 40.078,
        group: '',
    },
    Sc: {
        name: 'Escandio',
        symbol: 'Sc',
        atomicNumber: 21,
        atomicMass: 44.9559,
        group: '',
    },
    Ti: {
        name: 'Titanio',
        symbol: 'Ti',
        atomicNumber: 22,
        atomicMass: 47.867,
        group: '',
    },
    V: {
        name: 'Vanadio',
        symbol: 'V',
        atomicNumber: 23,
        atomicMass: 50.9415,
        group: '',
    },
    Cr: {
        name: 'Cromo',
        symbol: 'Cr',
        atomicNumber: 24,
        atomicMass: 51.9961,
        group: '',
    },
    Mn: {
        name: 'Manganeso',
        symbol: 'Mn',
        atomicNumber: 25,
        atomicMass: 54.9380,
        group: '',
    },
    Fe: {
        name: 'Hierro',
        symbol: 'Fe',
        atomicNumber: 26,
        atomicMass: 55.845,
        group: '',
    },
    Co: {
        name: 'Cobalto',
        symbol: 'Co',
        atomicNumber: 27,
        atomicMass: 58.9331,
        group: '',
    },
    Ni: {
        name: 'Níquel',
        symbol: 'Ni',
        atomicNumber: 28,
        atomicMass: 58.6934,
        group: '',
    },
    Cu: {
        name: 'Cobre',
        symbol: 'Cu',
        atomicNumber: 29,
        atomicMass: 63.546,
        group: '',
    },
    Zn: {
        name: 'Zinc',
        symbol: 'Zn',
        atomicNumber: 30,
        atomicMass:  65.38,
        group: '',
    },
    Ga: {
        name: 'Galio',
        symbol: 'Ga',
        atomicNumber: 31,
        atomicMass: 69.723,
        group: '',
    },
    Ge: {
        name: 'Germanio',
        symbol: 'Ge',
        atomicNumber: 32,
        atomicMass: 72.64,
        group: '',
    },
    As: {
        name: 'Arsénico',
        symbol: 'As',
        atomicNumber: 33,
        atomicMass: 74.9216,
        group: '',
    },
    Se: {
        name: 'Selenio',
        symbol: 'Se',
        atomicNumber: 34,
        atomicMass: 78.96,
        group: '',
    },
    Br: {
        name: 'Bromo',
        symbol: 'Br',
        atomicNumber: 35,
        atomicMass: 79.904,
        group: '',
    },
    Kr: {
        name: 'Kriptón',
        symbol: 'Kr',
        atomicNumber: 36,
        atomicMass: 83.798,
        group: '',
    },
    Rb: {
        name: 'Rubidio',
        symbol: 'Rb',
        atomicNumber: 37,
        atomicMass: 85.4678,
        group: '',
    },
    Sr: {
        name: 'Estroncio',
        symbol: 'Sr',
        atomicNumber: 38,
        atomicMass: 87.62,
        group: '',
    },
    Y: {
        name: 'Itrio',
        symbol: 'Y',
        atomicNumber: 39,
        atomicMass: 88.9058,
        group: '',
    },
    Zr: {
        name: 'Circonio',
        symbol: 'Zr',
        atomicNumber: 40,
        atomicMass: 91.224,
        group: '',
    },
    Nb: {
        name: 'Niobio',
        symbol: 'Nb',
        atomicNumber: 41,
        atomicMass: 92.9063,
        group: '',
    },
    Mo: {
        name: 'Molibdeno',
        symbol: 'Mo',
        atomicNumber: 42,
        atomicMass: 95.95,
        group: '',
    },
    Tc: {
        name: 'Tecnecio',
        symbol: 'Tc',
        atomicNumber: 43,
        atomicMass: 98,
        group: '',
    },
    Ru: {
        name: 'Rutenio',
        symbol: 'Ru',
        atomicNumber: 44,
        atomicMass: 101.07,
        group: '',
    },
    Rh: {
        name: 'Rodio',
        symbol: 'Rh',
        atomicNumber: 45,
        atomicMass: 102.905,
        group: '',
    },
    Pd: {
        name: 'Paladio',
        symbol: 'Pd',
        atomicNumber: 46,
        atomicMass: 106.42,
        group: '',
    },
    Ag: {
        name: 'Plata',
        symbol: 'Ag',
        atomicNumber: 47,
        atomicMass: 107.8682,
        group: '',
    },
    Cd: {
        name: 'Cadmio',
        symbol: 'Cd',
        atomicNumber: 48,
        atomicMass: 112.411,
        group: '',
    },
    In: {
        name: 'Indio',
        symbol: 'In',
        atomicNumber: 49,
        atomicMass: 114.818,
        group: '',
    },
    Sn: {
        name: 'Estaño',
        symbol: 'Sn',
        atomicNumber: 50,
        atomicMass: 118.71,
        group: '',
    },
    Sb: {
        name: 'Antimonio',
        symbol: 'Sb',
        atomicNumber: 51,
        atomicMass: 121.76,
        group: '',
    },
    Te: {
        name: 'Telurio',
        symbol: 'Te',
        atomicNumber: 52,
        atomicMass: 127.6,
        group: '',
    },
    I: {
        name: 'Yodo',
        symbol: 'I',
        atomicNumber: 53,
        atomicMass: 126.904,
        group: '',
    },
    Xe: {
        name: 'Xenón',
        symbol: 'Xe',
        atomicNumber: 54,
        atomicMass: 131.293,
        group: '',
    },
    Cs: {
        name: 'Cesio',
        symbol: 'Cs',
        atomicNumber: 55,
        atomicMass: 132.905,
        group: '',
    },
    Ba: {
        name: 'Bario',
        symbol: 'Ba',
        atomicNumber: 56,
        atomicMass: 137.327,
        group: '',
    },
    La: {
        name: 'Lantano',
        symbol: 'La',
        atomicNumber: 57,
        atomicMass: 138.905,
        group: '',
    },
    Hf: {
        name: 'Hafnio',
        symbol: 'Hf',
        atomicNumber: 72,
        atomicMass: 178.49,
        group: '',
    },
    Ta: {
        name: 'Tántalo',
        symbol: 'Ta',
        atomicNumber: 73,
        atomicMass: 180.947,
        group: '',
    },
    W: {
        name: 'Tungsteno',
        symbol: 'W',
        atomicNumber: 74,
        atomicMass: 183.84,
        group: '',
    },
    Re: {
        name: 'Renio',
        symbol: 'Re',
        atomicNumber: 75,
        atomicMass: 186.207,
        group: '',
    },
    Os: {
        name: 'Osmio',
        symbol: 'Os',
        atomicNumber: 76,
        atomicMass: 190.23,
        group: '',
    },
    Ir: {
        name: 'Iridio',
        symbol: 'Ir',
        atomicNumbe: 77,
        atomicMass: 192.217,
        group: '',
    },
    Pt: {
        name: 'Platino',
        symbol: 'Pt',
        atomicNumber: 78,
        atomicMass: 195.084,
        group: '',
    },
    Au: {
        name: 'Oro',
        symbol: 'Au',
        atomicNumber: 79,
        atomicMass: 196.966,
        group: '',
    },
    Hg: {
        name: 'Mercurio',
        symbol: 'Hg',
        atomicNumber: 80,
        atomicMass: 200.59,
        group: '',
    },
    Tl: {
        name: 'Talio',
        symbol: 'Tl',
        atomicNumber: 81,
        atomicMass: 204.383,
        group: '',
    },
    Pb: {
        name: 'Plomo',
        symbol: 'Pb',
        atomicNumber: 82,
        atomicMass: 207.2,
        group: '',
    },
    Bi: {
        name: 'Bismuto',
        symbol: 'Bi',
        atomicNumber: 83,
        atomicMass: 208.980,
        group: '',
    },
    Po: {
        name: 'Polonio',
        symbol: 'Po',
        atomicNumber: 84,
        atomicMass: 209,
        group: '',
    },
    At: {
        name: 'Astato',
        symbol: 'At',
        atomicNumber: 85,
        atomicMass: 210,
        group: '',
    },
    Rn: {
        name: 'Radón',
        symbol: 'Rn',
        atomicNumber: 86,
        atomicMass: 222,
        group: '',
    },
    Fr: {
        name: 'Francio',
        symbol: 'Fr',
        atomicNumber: 87,
        atomicMass: 223,
        group: '',
    },
    Ra: {
        name: 'Radio',
        symbol: 'Ra',
        atomicNumber: 88,
        atomicMass: 226,
        group: '',
    },
    Ac: {
        name: 'Actinio',
        symbol: 'Ac',
        atomicNumber: 89,
        atomicMass: 227,
        group: '',
    },
    Rf: {
        name: 'Rutherfordio',
        symbol: 'Rf',
        atomicNumber: 104,
        atomicMass: 267,
        group: '',
    },
    Db: {
        name: 'Dubnio',
        symbol: 'Db',
        atomicNumber: 105,
        atomicMass: 262,
        group: '',
    },
    Sg: {
        name: 'Seaborgio',
        symbol: 'Sg',
        atomicNumber: 106,
        atomicMass: 269,
        group: '',
    },
    Bh: {
        name: 'Bohrio',
        symbol: 'Bh',
        atomicNumber: 107,
        atomicMass: 264,
        group: '',
    },
    Hs: {
        name: 'Hasio',
        symbol: 'Hs',
        atomicNumber: 108,
        atomicMass: 269,
        group: '',
    },
    Mt: {
        name: 'Meitnerio',
        symbol: 'Mt',
        atomicNumber: 109,
        atomicMass: 278,
        group: '',
    },
    Ds: {
        name: 'Darmstatio',
        symbol: 'Ds',
        atomicNumber: 110,
        atomicMass: 281,
        group: '',
    },
    Rg: {
        name: 'Roentgenio',
        symbol: 'Rg',
        atomicNumber: 111,
        atomicMass: 282,
        group: '',
    },
    Cn: {
        name: 'Copernicio',
        symbol: 'Cn',
        atomicNumber: 112,
        atomicMass: 285,
        group: '',
    },
    Nh: {
        name: 'Nihonio',
        symbol: 'Nh',
        atomicNumber: 113,
        atomicMass: 286,
        group: '',
    },
    Fl: {
        name: 'Flerovio',
        symbol: 'Fl',
        atomicNumber: 114,
        atomicMass: 289,
        group: '',
    },
    Mc: {
        name: 'Moscovio',
        symbol: 'Mc',
        atomicNumber: 115,
        atomicMass: 289,
        group: '',
    },
    Lv: {
        name: 'Livermorio',
        symbol: 'Lv',
        atomicNumber: 116,
        atomicMass: 293,
        group: '',
    },
    Ts: {
        name: 'Teneso',
        symbol: 'Ts',
        atomicNumber: 117,
        atomicMass: 294,
        group: '',
    },
    Og: {
        name: 'Oganesón',
        symbol: 'Og',
        atomicNumber: 118,
        atomicMass: 294,
        group: '',
    },
    Ce: {
        name: 'Cerio',
        symbol: 'Ce',
        atomicNumber: 58,
        atomicMass: 140.116,
        group: '',
    },
    Pr: {
        name: 'Praseodimio',
        symbol: 'Pr',
        atomicNumber: 59,
        atomicMass: 140.907,
        group: '',
    },
    Nd: {
        name: 'Neodimio',
        symbol: 'Nd',
        atomicNumber: 60,
        atomicMass: 144.242,
        group: '',
    },
    Pm: {
        name: 'Prometio',
        symbol: 'Pm',
        atomicNumber: 61,
        atomicMass: 145,
        group: '',
    },
    Sm: {
        name: 'Samario',
        symbol: 'Sm',
        atomicNumber: 62,
        atomicMass: 150.36,
        group: '',
    },
    Eu: {
        name: 'Europio',
        symbol: 'Eu',
        atomicNumber: 63,
        atomicMass: 151.964,
        group: '',
    },
    Gd: {
        name: 'Gadolinio',
        symbol: 'Gd',
        atomicNumber: 64,
        atomicMass: 157.25,
        group: '',
    },
    Tb: {
        name: 'Terbio',
        symbol: 'Tb',
        atomicNumber: 65,
        atomicMass: 158.925,
        group: '',
    },
    Dy: {
        name: 'Disprosio',
        symbol: 'Dy',
        atomicNumber: 66,
        atomicMass: 162.5,
        group: '',
    },
    Ho: {
        name: 'Holmio',
        symbol: 'Ho',
        atomicNumber: 67,
        atomicMass: 164.930,
        group: '',
    },
    Er: {
        name: 'Erbio',
        symbol: 'Er',
        atomicNumber: 68,
        atomicMass: 167.259,
        group: '',
    },
    Tm: {
        name: 'Tulio',
        symbol: 'Tm',
        atomicNumber: 69,
        atomicMass: 168.934,
        group: '',
    },
    Yb: {
        name: 'Iterbio',
        symbol: 'Yb',
        atomicNumber: 70,
        atomicMass: 173.04,
        group: '',
    },
    Lu: {
        name: 'Lutecio',
        symbol: 'Lu',
        atomicNumber: 71,
        atomicMass: 174.967,
        group: '',
    },
    Th: {
        name: 'Torio',
        symbol: 'Th',
        atomicNumber: 90,
        atomicMass: 232.038,
        group: '',
    },
    Pa: {
        name: 'Protactinio',
        symbol: 'Pa',
        atomicNumber: 91,
        atomicMass: 231.035,
        group: '',
    },
    U: {
        name: 'Uranio',
        symbol: 'U',
        atomicNumber: 92,
        atomicMass: 238.028,
        group: '',
    },
    Np: {
        name: 'Neptunio',
        symbol: 'Np',
        atomicNumber: 93,
        atomicMass: 237.048,
        group: '',
    },
    Pu: {
        name: 'Plutonio',
        symbol: 'Pu',
        atomicNumber: 94,
        atomicMass: 244,
        group: '',
    },
    Am: {
        name: 'Americio',
        symbol: 'Am',
        atomicNumber: 95,
        atomicMass: 243,
        group: '',
    },
    Cm: {
        name: 'Curio',
        symbol: 'Cm',
        atomicNumber: 96,
        atomicMass: 247,
        group: '',
    },
    Bk: {
        name: 'Berkelio',
        symbol: 'Bk',
        atomicNumber: 97,
        atomicMass: 247,
        group: '',
    },
    Cf: {
        name: 'Californio',
        symbol: 'Cf',
        atomicNumber: 98,
        atomicMass: 251,
        group: '',
    },
    Es: {
        name: 'Einstenio',
        symbol: 'Es',
        atomicNumber: 99,
        atomicMass: 252,
        group: '',
    },
    Fm: {
        name: 'Fermio',
        symbol: 'Fm',
        atomicNumber: 100,
        atomicMass: 257,
        group: '',
    },
    Md: {
        name: 'Mendelevio',
        symbol: 'Md',
        atomicNumber: 101,
        atomicMass: 258,
        group: '',
    },
    No: {
        name: 'Nobelio',
        symbol: 'No',
        atomicNumber: 102,
        atomicMass: 259,
        group: '',
    },
    Lr: {
        name: 'Lawrencio',
        symbol: 'Lr',
        atomicNumber: 103,
        atomicMass: 262,
        group: '',
    },
};